### ISSUE TITLE
create MD failed if don't set bitmap

### ISSUE THREAD

**Issue by guazhangRH** [storaged-project/libblockdev#1013]
```
TESTRAID ['/dev/loop0', '/dev/loop1'] raid0 {'size': '3G'}
Traceback (most recent call last):
  File "/home/cryptsetup_libblockdev/luks_main.py", line 128, in <module>
    target = obj.make_test_target(i)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cryptsetup_libblockdev/luks.py", line 1173, in make_test_target
    dev = self.add_raid(self.raid_name, self.raid_mem, self.raid_level, size="3G")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cryptsetup_libblockdev/luks.py", line 942, in add_raid
    succ = bd.md_create(raid_name, raid_level, raid_mem, **kwrags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/gi/overrides/BlockDev.py", line 1023, in md_create
    return _md_create(device_name, level, disks, spares, version, bitmap, chunk_size, extra)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Must be string, not bool
```
kernel-6.8.0-0.rc3.20240209git1f719a2f3fa6.31.el10.x86_64
libblockdev-3.1.0-2.el10.x86_64

```
_md_create = BlockDev.md_create
@override(BlockDev.md_create)
def md_create(device_name, level, disks, spares=0, version=None, bitmap=False, chunk_size=0, extra=None, **kwargs):
    extra = _get_extra(extra, kwargs)
    return _md_create(device_name, level, disks, spares, version, bitmap, chunk_size, extra)
__all__.append("md_create")
```

update the bitmap=False to None

**Comment by vojtechtrefny** [comment]
Closed via #1014
