### ISSUE TITLE
Assertion error in tests/library_test.py

### ISSUE THREAD

**Issue by mbiebl** [storaged-project/libblockdev#944]
Version: 3.0.2-1

I'm currently trying to run the test suite but I run into the following failures:
```
======================================================================
FAIL: test_force_plugin (library_test.PluginsTestCase.test_force_plugin)
Verify that forcing plugin to be used works as expected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest.ZLSthX/tree/tests/library_test.py", line 240, in test_force_plugin
    self.assertEqual(BlockDev.lvm_get_max_lv_size(), 1024)
AssertionError: 9223372036854775808 != 1024

======================================================================
FAIL: test_plugin_priority (library_test.PluginsTestCase.test_plugin_priority)
Verify that preferring plugin to be used works as expected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest.ZLSthX/tree/tests/library_test.py", line 283, in test_plugin_priority
    self.assertEqual(BlockDev.lvm_get_max_lv_size(), 1024)
AssertionError: 9223372036854775808 != 1024

======================================================================
FAIL: test_reload (library_test.PluginsTestCase.test_reload)
Verify that reloading plugins works as expected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest.ZLSthX/tree/tests/library_test.py", line 198, in test_reload
    self.assertEqual(BlockDev.lvm_get_max_lv_size(), 1024)
AssertionError: 9223372036854775808 != 1024

----------------------------------------------------------------------
Ran 487 tests in 2465.088s

FAILED (failures=3, errors=2, skipped=21)
```

From a cursory glance at tests/library_test.py, the problem might be the following code:
```
        os.system ("rm -f src/plugins/.libs/libbd_lvm2.so")
```

I see several issues:
- The test seems to try to compile the library on the fly and does not use the system provided libblockdev-lvm3
-  The library name appears to be incorrect, shouldn't it use `libbd_lvm.so.3`

**Comment by mbiebl** [comment]
nvm: Just saw
```
        os.system("cp src/plugins/.libs/libbd_lvm.so src/plugins/.libs/libbd_lvm2.so")
```

What remains, is the need to need to compile those plugins on the fly, ie. I will probably need to update my test bed to include all build dependencies.

**Comment by vojtechtrefny** [comment]
These tests definitely need to fail sooner (and with a better error message) when the compilation fails. If you don't want run these tests, you can skip them by using `--exclude-tags sourceonly` argument for the `run_tests.py` script.

**Comment by mbiebl** [comment]
A test run with `--exclude-tags sourceonly` now succeeds. I also tried one with the build dependencies installed and then I get
```
======================================================================
ERROR: test_force_plugin (library_test.PluginsTestCase.test_force_plugin)
Verify that forcing plugin to be used works as expected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest.OPvIxF/build.8db/src/tests/library_test.py", line 237, in test_force_plugin
    self.assertTrue(BlockDev.reinit([ps], True, None))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/autopkgtest.OPvIxF/build.8db/src/src/python/gi/overrides/BlockDev.py", line 144, in reinit
    return _reinit(require_plugins, reload, log_func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-bd-init-error-quark: Failed to load plugins (1)

======================================================================
FAIL: test_plugin_priority (library_test.PluginsTestCase.test_plugin_priority)
Verify that preferring plugin to be used works as expected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest.OPvIxF/build.8db/src/tests/library_test.py", line 282, in test_plugin_priority
    self.assertEqual(BlockDev.get_plugin_soname(BlockDev.Plugin.LVM), "libbd_lvm2.so.3")
AssertionError: 'libbd_lvm.so.3' != 'libbd_lvm2.so.3'
- libbd_lvm.so.3
+ libbd_lvm2.so.3
?          +


======================================================================
FAIL: test_reload (library_test.PluginsTestCase.test_reload)
Verify that reloading plugins works as expected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest.OPvIxF/build.8db/src/tests/library_test.py", line 198, in test_reload
    self.assertEqual(BlockDev.lvm_get_max_lv_size(), 1024)
AssertionError: 9223372036854775808 != 1024

----------------------------------------------------------------------
Ran 487 tests in 2467.168s

FAILED (failures=2, errors=1, skipped=21)
```

**Comment by mbiebl** [comment]
woohoo, with `--exclude-tags sourceonly`, -tools being enabled (#943)  and `allow-stderr` (#947)

```
----------------------------------------------------------------------
Ran 484 tests in 3311.924s

OK (skipped=21)
autopkgtest [17:03:16]: test upstream: -----------------------]
autopkgtest [17:03:17]: test upstream:  - - - - - - - - - - results - - - - - - - - - -
upstream             PASS
autopkgtest [17:03:18]: @@@@@@@@@@@@@@@@@@@@ summary
upstream             PASS
qemu-system-x86_64: terminating on signal 15 from pid 176224 (/usr/bin/python3)
```
